app:
  dashboard_url: "https://pangolin.internal"
  log_level: debug
server:
  cors:
    origins:
        - "https://pangolin.internal"
    methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "PATCH"
    allowed_headers:
        - "X-CSRF-Token"
        - "Content-Type"
    credentials: true
  secret: 1b5f55122e7611f0bf624bafe52c91daadsfjhksd234
gerbil:
  base_endpoint: pangolin.fosrl.io
flags:
  require_email_verification: true
  disable_signup_without_invite: false
  disable_user_create_org: true
  allow_base_domain_resources: false
  disable_local_sites: false
  disable_basic_wireguard_sites: true
  enable_integration_api: true
  disable_config_managed_domains: true
  hide_supporter_key: true
  enable_redis: true
  enable_clients: true
  allow_raw_resources: true
email:
  smtp_host: "email-smtp.us-east-1.amazonaws.com"
  smtp_port: 587
  smtp_user: "AKIATFBMPNE6PKLOK4MK"
  smtp_pass: "BHStM/Nz9B9Crt3YePtsVDnjEp4MZmXqoQvZXWk0MQTC"
  no_reply: no-reply@fossorial.io
